services:
  mongodb:
    image: mongo:latest
    container_name: hmongo
    networks:
      - hisabnet
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  asrdashboard:
    depends_on:
      - mongodb
    platform: linux/x86_64
    image: hisabasr:latest
    build:
      context: ./deploy
      dockerfile: Dockerfile
    ports:
      - 8085:3000
    environment:
      - MONGO_URL=mongodb://root:example@mongodb:27017/asr?authSource=admin
      - ROOT_URL=http://localhost:8085
      - NODE_ENV=dev
    networks:
      - hisabnet

networks:
  hisabnet:

volumes:
  mongo-data:
    driver: local
